/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import questao2.Empresa;
import questao2.Funcionario;
import questao2.NomeVazioException;
import questao2.Programador;
import questao2.Venda;
import questao2.Vendedor;

/**
 *
 * @author mdspezia
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Empresa empresa;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNomeFuncionario = new javax.swing.JTextField();
        jtfSalarioBase = new javax.swing.JTextField();
        jrbProgramador = new javax.swing.JRadioButton();
        jrbVendedor = new javax.swing.JRadioButton();
        jrbComum = new javax.swing.JRadioButton();
        jbtAddFuncionario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel0 = new javax.swing.JLabel();
        jtfNomeEmpresa = new javax.swing.JTextField();
        jbtAddEmpresa = new javax.swing.JButton();
        jbtDados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empresa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionário"));
        jPanel1.setEnabled(false);

        jLabel1.setText("Nome:");

        jLabel2.setText("Salário: R$");

        jLabel3.setText("Tipo:");

        jtfNomeFuncionario.setEnabled(false);

        jtfSalarioBase.setEnabled(false);

        buttonGroup1.add(jrbProgramador);
        jrbProgramador.setText("Programador");
        jrbProgramador.setEnabled(false);

        buttonGroup1.add(jrbVendedor);
        jrbVendedor.setText("Vendedor");
        jrbVendedor.setEnabled(false);

        buttonGroup1.add(jrbComum);
        jrbComum.setSelected(true);
        jrbComum.setText("Comum");
        jrbComum.setEnabled(false);

        jbtAddFuncionario.setText("Adicionar");
        jbtAddFuncionario.setEnabled(false);
        jbtAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbProgramador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtAddFuncionario)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbVendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbComum)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jrbProgramador)
                    .addComponent(jrbVendedor)
                    .addComponent(jrbComum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtAddFuncionario)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa"));

        jLabel0.setText("Nome:");

        jbtAddEmpresa.setText("OK");
        jbtAddEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddEmpresaActionPerformed(evt);
            }
        });

        jbtDados.setText("Listar dados");
        jbtDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jbtAddEmpresa)
                        .addGap(34, 34, 34)
                        .addComponent(jbtDados)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel0)
                    .addComponent(jtfNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAddEmpresa)
                    .addComponent(jbtDados))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAddEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddEmpresaActionPerformed
        try {
            empresa = new Empresa(jtfNomeEmpresa.getText());

            jPanel1.setEnabled(true);
            jtfNomeFuncionario.setEnabled(true);
            jtfSalarioBase.setEnabled(true);
            jbtAddFuncionario.setEnabled(true);
            jrbProgramador.setEnabled(true);
            jrbVendedor.setEnabled(true);
            jrbComum.setEnabled(true);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (NomeVazioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtAddEmpresaActionPerformed

    private void jbtAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddFuncionarioActionPerformed
        try {
            if (jtfSalarioBase.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Salário deve ser informado");
            } else {
                if (jrbComum.isSelected()) {
                    empresa.incluirFuncionario(new Funcionario(jtfNomeFuncionario.getText(), Double.parseDouble(jtfSalarioBase.getText())));
                } else if (jrbProgramador.isSelected()) {
                    Programador programador = new Programador(jtfNomeFuncionario.getText(), Double.parseDouble(jtfSalarioBase.getText()));
                    empresa.incluirFuncionario(programador);
                    TelaProgramador telaProgramador = new TelaProgramador(programador);
                    telaProgramador.setVisible(true);
                } else {
                    String nome = jtfNomeFuncionario.getText();
                    double salario = Double.parseDouble(jtfSalarioBase.getText());
                    TelaVendedor telaVendedor = new TelaVendedor(nome, salario, empresa);
                    telaVendedor.setVisible(true);
                }
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (NomeVazioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtAddFuncionarioActionPerformed

    private void jbtDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDadosActionPerformed
        String dados = empresa.getNome() + "\n";

        for (Funcionario f : empresa.getFuncionarios()) {
            dados += f.getNome() + "\nR$ " + f.getSalarioBase() + "\n";
            if (f instanceof Programador) {
                //Programador p = (Programador) f;
                for (String s : ((Programador) f).getLinguagens()) {
                    dados += s + " - ";
                }
                dados += "\n";
            } else if (f instanceof Vendedor) {
                Vendedor v = (Vendedor) f;
                dados += "Comissão: " + v.getPercentualComissao() + "\n";
                for (Venda venda : v.getVendas()) {
                    dados += venda.getValor() + " - ";
                }
                dados += "\n";
            }
            dados += "Salário: " + f.calcularSalario() + "\n";
        }
        JOptionPane.showMessageDialog(this, dados);
    }//GEN-LAST:event_jbtDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtAddEmpresa;
    private javax.swing.JButton jbtAddFuncionario;
    private javax.swing.JButton jbtDados;
    private javax.swing.JRadioButton jrbComum;
    private javax.swing.JRadioButton jrbProgramador;
    private javax.swing.JRadioButton jrbVendedor;
    private javax.swing.JTextField jtfNomeEmpresa;
    private javax.swing.JTextField jtfNomeFuncionario;
    private javax.swing.JTextField jtfSalarioBase;
    // End of variables declaration//GEN-END:variables
}
