/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import questao2.Empresa;
import questao2.NomeVazioException;
import questao2.Venda;
import questao2.Vendedor;

/**
 *
 * @author mdspezia
 */
public class TelaVendedor extends javax.swing.JFrame {

    private String nomeVendedor;
    private double salario;
    private Empresa empresa;
    private Vendedor vendedor;
    /**
     * Creates new form TelaVendedor
     */
    public TelaVendedor(String nome, double salario, Empresa empresa) {
        initComponents();
        this.nomeVendedor = nome;
        this.salario = salario;
        this.empresa = empresa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfComissao = new javax.swing.JTextField();
        jtfVenda = new javax.swing.JTextField();
        jbtAddComissao = new javax.swing.JButton();
        jbtAddVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro do Vendedor");

        jLabel1.setText("Comissão:");

        jLabel2.setText("Venda: R$");

        jtfVenda.setEnabled(false);

        jbtAddComissao.setText("OK");
        jbtAddComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddComissaoActionPerformed(evt);
            }
        });

        jbtAddVenda.setText("Adicionar");
        jbtAddVenda.setEnabled(false);
        jbtAddVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtAddVenda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtAddComissao)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtAddComissao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtAddVenda))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAddComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddComissaoActionPerformed
        try {
            vendedor = new Vendedor(Double.parseDouble(jtfComissao.getText()), nomeVendedor, salario);
        } catch (NomeVazioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        empresa.incluirFuncionario(vendedor);
        jtfVenda.setEnabled(true);
        jbtAddVenda.setEnabled(true);
    }//GEN-LAST:event_jbtAddComissaoActionPerformed

    private void jbtAddVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddVendaActionPerformed
        vendedor.incluirVenda(new Venda(Double.parseDouble(jtfVenda.getText())));
        jtfVenda.setText("");
    }//GEN-LAST:event_jbtAddVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtAddComissao;
    private javax.swing.JButton jbtAddVenda;
    private javax.swing.JTextField jtfComissao;
    private javax.swing.JTextField jtfVenda;
    // End of variables declaration//GEN-END:variables
}
