/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Ponto;
import model.Quadrante;

/**
 *
 * @author mdspezia
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfX = new javax.swing.JTextField();
        jtfY = new javax.swing.JTextField();
        jbtAvaliar = new javax.swing.JButton();
        jcbEixoX = new javax.swing.JCheckBox();
        jcbEixoY = new javax.swing.JCheckBox();
        jcbQuadrante1 = new javax.swing.JCheckBox();
        jcbQuadrante2 = new javax.swing.JCheckBox();
        jcbQuadrante3 = new javax.swing.JCheckBox();
        jcbQuadrante4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eixo X:");

        jLabel2.setText("Eixo Y:");

        jLabel3.setText("Posição:");

        jtfX.setPreferredSize(new java.awt.Dimension(80, 22));

        jtfY.setPreferredSize(new java.awt.Dimension(80, 22));

        jbtAvaliar.setText("Avaliar");
        jbtAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAvaliarActionPerformed(evt);
            }
        });

        jcbEixoX.setText("Incide sobre o Eixo X");
        jcbEixoX.setEnabled(false);

        jcbEixoY.setText("Incide sobre o Eixo Y");
        jcbEixoY.setEnabled(false);

        jcbQuadrante1.setText("No 1º Quadrante");
        jcbQuadrante1.setEnabled(false);

        jcbQuadrante2.setText("No 2º Quadrante");
        jcbQuadrante2.setEnabled(false);

        jcbQuadrante3.setText("No 3º Quadrante");
        jcbQuadrante3.setEnabled(false);

        jcbQuadrante4.setText("No 4º Quadrante");
        jcbQuadrante4.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbQuadrante4)
                    .addComponent(jcbQuadrante3)
                    .addComponent(jcbQuadrante2)
                    .addComponent(jcbQuadrante1)
                    .addComponent(jcbEixoY)
                    .addComponent(jcbEixoX)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(76, 76, 76)))
                        .addGap(63, 63, 63)
                        .addComponent(jbtAvaliar)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jbtAvaliar)))
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbEixoX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbEixoY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbQuadrante1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbQuadrante2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbQuadrante3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbQuadrante4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAvaliarActionPerformed
        try {
            int x = Integer.parseInt(jtfX.getText());
            int y = Integer.parseInt(jtfY.getText());

            Ponto p = new Ponto(x, y);

            jcbEixoX.setSelected(false);
            jcbEixoY.setSelected(false);
            jcbQuadrante1.setSelected(false);
            jcbQuadrante2.setSelected(false);
            jcbQuadrante3.setSelected(false);
            jcbQuadrante4.setSelected(false);

            if (p.estaIncidindoSobreX() == true) {
                jcbEixoX.setSelected(true);
            }
            if (p.estaIncidindoSobreY()) {
                jcbEixoY.setSelected(true);
            }
            if (p.identificarQuadrante() == Quadrante.PRIMEIRO) {
                jcbQuadrante1.setSelected(true);
            }
            if (p.identificarQuadrante() == Quadrante.SEGUNDO) {
                jcbQuadrante2.setSelected(true);
            }
            if (p.identificarQuadrante() == Quadrante.TERCEIRO) {
                jcbQuadrante3.setSelected(true);
            }
            if (p.identificarQuadrante() == Quadrante.QUARTO) {
                jcbQuadrante4.setSelected(true);
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Não podem haver valores vazios");
        }
    }//GEN-LAST:event_jbtAvaliarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtAvaliar;
    private javax.swing.JCheckBox jcbEixoX;
    private javax.swing.JCheckBox jcbEixoY;
    private javax.swing.JCheckBox jcbQuadrante1;
    private javax.swing.JCheckBox jcbQuadrante2;
    private javax.swing.JCheckBox jcbQuadrante3;
    private javax.swing.JCheckBox jcbQuadrante4;
    private javax.swing.JTextField jtfX;
    private javax.swing.JTextField jtfY;
    // End of variables declaration//GEN-END:variables
}
