/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package questao_extra;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mdspezia
 */
public class Tela extends JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        contas = new ContaBancaria[10];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfNumeroConta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfTitular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfValor = new javax.swing.JTextField();
        jbtCriarConta = new javax.swing.JButton();
        jbtDepositar = new javax.swing.JButton();
        jlbSaldo = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conta Bancaria");
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setText("Número conta");
        getContentPane().add(jLabel1);

        jtfNumeroConta.setPreferredSize(new java.awt.Dimension(80, 22));
        getContentPane().add(jtfNumeroConta);

        jLabel2.setText("Titular");
        getContentPane().add(jLabel2);

        jtfTitular.setPreferredSize(new java.awt.Dimension(80, 22));
        getContentPane().add(jtfTitular);

        jLabel3.setText("Valor");
        getContentPane().add(jLabel3);

        jtfValor.setPreferredSize(new java.awt.Dimension(80, 22));
        getContentPane().add(jtfValor);

        jbtCriarConta.setText("Criar conta");
        jbtCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCriarContaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtCriarConta);

        jbtDepositar.setText("Depositar");
        jbtDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDepositarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtDepositar);

        jlbSaldo.setText("Saldo");
        getContentPane().add(jlbSaldo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCriarContaActionPerformed
        String numeroConta = jtfNumeroConta.getText();

        if (buscar(numeroConta) == null && quantidadeContas < contas.length) {
            String titular = jtfTitular.getText();
            ContaBancaria conta = new ContaBancaria(numeroConta, titular);
            contas[quantidadeContas] = conta;
            quantidadeContas++;

            JOptionPane.showMessageDialog(this, "Conta criada");
        } else {
            JOptionPane.showMessageDialog(this, "Conta já existe ou já está cheio");
        }
    }//GEN-LAST:event_jbtCriarContaActionPerformed

    private void jbtDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDepositarActionPerformed
        String numeroConta = jtfNumeroConta.getText();
        ContaBancaria conta = buscar(numeroConta);
        if (conta != null) {
            float valor = Float.parseFloat(jtfValor.getText());
            conta.depositar(valor);
            jlbSaldo.setText("Saldo R$" + conta.getSaldo());
        } else {
            JOptionPane.showMessageDialog(null, "Conta não existe");
    }//GEN-LAST:event_jbtDepositarActionPerformed

    }

    private ContaBancaria buscar(String numeroConta) {
        for (ContaBancaria c : contas) {
            if (c != null && c.getNumero().trim().equalsIgnoreCase(numeroConta)) {
                return c;
            }
        }
        return null;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }
    private ContaBancaria[] contas;
    private int quantidadeContas;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtCriarConta;
    private javax.swing.JButton jbtDepositar;
    private javax.swing.JLabel jlbSaldo;
    private javax.swing.JTextField jtfNumeroConta;
    private javax.swing.JTextField jtfTitular;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
