/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import model.Comanda;
import model.Dinheiro;
import model.Pagamento;
import model.TipoBuffet;

/**
 *
 * @author mdspezia
 */
public class TelaPagamento extends javax.swing.JFrame {

    private TelaPrincipal telaP;
    DecimalFormat df = new DecimalFormat("0.00");
    
    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento(TelaPrincipal telaPrincipal) {
        this.telaP = telaPrincipal;
        //this.comanda = comanda;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtTroco = new javax.swing.JButton();
        jtfValorPagoDin = new javax.swing.JTextField();
        jlbTotalPagarDin = new javax.swing.JLabel();
        jlbDescontoDin = new javax.swing.JLabel();
        jlbTroco = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrbDinheiro = new javax.swing.JRadioButton();
        jrbOutro = new javax.swing.JRadioButton();
        jbtPagamento = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbTotalPagarOutro = new javax.swing.JLabel();
        jlbDescontoOutro = new javax.swing.JLabel();
        jbtPagamentoOutro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dinheiro"));
        jPanel1.setEnabled(false);

        jLabel2.setText("Valor pago: R$");

        jLabel3.setText("Total pagar:");

        jLabel4.setText("Desconto:");

        jLabel5.setText("Troco:");

        jbtTroco.setText("Calcular troco");
        jbtTroco.setEnabled(false);
        jbtTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTrocoActionPerformed(evt);
            }
        });

        jtfValorPagoDin.setEnabled(false);
        jtfValorPagoDin.setPreferredSize(new java.awt.Dimension(80, 22));

        jlbTotalPagarDin.setText("R$ ");

        jlbDescontoDin.setText("R$");

        jlbTroco.setText("R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfValorPagoDin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jlbTroco)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlbDescontoDin))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbTotalPagarDin)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(jbtTroco)
                        .addGap(62, 62, 62))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfValorPagoDin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlbTotalPagarDin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jlbDescontoDin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtTroco)
                        .addGap(13, 13, 13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jlbTroco))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de pagamento"));

        jLabel1.setText("Tipo de pagamento:");

        buttonGroup1.add(jrbDinheiro);
        jrbDinheiro.setText("Dinheiro");

        buttonGroup1.add(jrbOutro);
        jrbOutro.setText("Outro");

        jbtPagamento.setText("OK");
        jbtPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbDinheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbOutro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jbtPagamento)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jrbDinheiro)
                    .addComponent(jrbOutro)
                    .addComponent(jbtPagamento))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Outro"));
        jPanel3.setEnabled(false);
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(408, 110));

        jLabel6.setText("Total pagar:");

        jLabel7.setText("Desconto:");

        jlbTotalPagarOutro.setText("R$");

        jlbDescontoOutro.setText("R$");

        jbtPagamentoOutro.setText("Realizar Pagamento");
        jbtPagamentoOutro.setEnabled(false);
        jbtPagamentoOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPagamentoOutroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbTotalPagarOutro))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jlbDescontoOutro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jbtPagamentoOutro)
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jlbTotalPagarOutro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jlbDescontoOutro)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jbtPagamentoOutro)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jbtPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPagamentoActionPerformed
        try {
            if (jrbDinheiro.isSelected()) {
                jtfValorPagoDin.setEnabled(true);
                jbtTroco.setEnabled(true);
                jPanel1.setEnabled(true);
                jPanel3.setEnabled(false);

                //dinheiro = new Dinheiro(comanda, Float.parseFloat(jtfValorPagoDin.getText()));
                //jlbTotalPagarDin.setText("R$ " + dinheiro.calcularTotalComanda());
                //jlbDescontoDin.setText("R$ " + dinheiro.calcularDesconto());
            } else if (jrbOutro.isSelected()) {
                jPanel3.setEnabled(true);
                jbtPagamentoOutro.setEnabled(true);
                jtfValorPagoDin.setEnabled(false);
                jbtTroco.setEnabled(false);
                jPanel1.setEnabled(false);

                //jlbTotalPagarOutro.setText("R$ " + pagamento.calcularTotalComanda());
                //jlbDescontoOutro.setText("R$ " + pagamento.calcularDesconto());
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jbtPagamentoActionPerformed

    private void jbtTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTrocoActionPerformed
        try {
            Dinheiro dinheiro = new Dinheiro(telaP.comanda, Float.parseFloat(jtfValorPagoDin.getText()));
            dinheiro.pagar(Float.parseFloat(jtfValorPagoDin.getText()));
            jlbTotalPagarDin.setText("R$ " + df.format(dinheiro.calcularTotalComanda()));
            jlbDescontoDin.setText("R$ " + df.format(dinheiro.calcularDesconto()));
            jlbTroco.setText("R$ " + df.format(dinheiro.calcularTroco()));

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jbtTrocoActionPerformed

    private void jbtPagamentoOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPagamentoOutroActionPerformed
        try {
            Pagamento pagamento = new Pagamento(telaP.comanda);
            jlbTotalPagarOutro.setText("R$ " + df.format(pagamento.calcularTotalComanda()));
            jlbDescontoOutro.setText("R$ " + df.format(pagamento.calcularDesconto()));
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jbtPagamentoOutroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtPagamento;
    private javax.swing.JButton jbtPagamentoOutro;
    private javax.swing.JButton jbtTroco;
    private javax.swing.JLabel jlbDescontoDin;
    private javax.swing.JLabel jlbDescontoOutro;
    private javax.swing.JLabel jlbTotalPagarDin;
    private javax.swing.JLabel jlbTotalPagarOutro;
    private javax.swing.JLabel jlbTroco;
    private javax.swing.JRadioButton jrbDinheiro;
    private javax.swing.JRadioButton jrbOutro;
    private javax.swing.JTextField jtfValorPagoDin;
    // End of variables declaration//GEN-END:variables
}
